site:
  name: 'Lucrinho'
  site: 'https://lucrinho.com'
  base: '/'
  trailingSlash: false
  googleSiteVerificationId: false

# Default SEO metadata
metadata:
  title:
    default: 'Lucrinho'
    template: '%s — Lucrinho'
  description: 'Sua descrição do site aqui'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 'Lucrinho'
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@lucrinho'
    site: '@lucrinho'
    cardType: summary_large_image

i18n:
  language: pt-BR
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/blog/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'categoria'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'


